services:
  router:
    image:    registry.gitlab.com/rny3/brande/router:v0.0.19
    ports:    ["80:80", "443:443", "443:443/udp"]
    volumes:  [router_data:/data, router_config:/config]
    networks: [qabo_network]
    secrets:  [cloudflare_api_token]

volumes:
  router_data:
  router_config:

networks:
  qabo_network: {name: qabo_network}

secrets:
  cloudflare_api_token: {file: ./secrets/cloudflare_api_token.secret}
