services:
  caddy:
    image: caddy:latest
    image: registry.gitlab.com/rny3/brande/router:latest
    ports:
      - "8080:80"
      - "8443:443"
      - "8443:443/udp"  # HTTP/3
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - webhook

  webhook:
    build: .
    target: development
    # environment:
    #   - APP_SECRET=${FB_APP_SECRET}
    #   - VERIFY_TOKEN=${FB_VERIFY_TOKEN}
    #   - PAGE_ACCESS_TOKEN=${FB_PAGE_ACCESS_TOKEN}
    volumes:
      - ./src:/app/src

volumes:
  caddy_data:
  caddy_config:
