stages:
  - build

build:facebook_dm:image:
  image: docker:24.0.5
  stage: build
  services:
    - docker:24.0.5-dind
  variables:
    DOCKER_DRIVER: overlay2
    IMAGE_NAME: "$CI_REGISTRY_IMAGE/facebook_dm"
    IMAGE_TAG: "$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA"
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
    - cd services/facebook_dm/
  script:
    - docker build --target production -t "$IMAGE_NAME:$IMAGE_TAG" -t "$IMAGE_NAME:latest" .
    - docker push "$IMAGE_NAME:$IMAGE_TAG"
    - docker push "$IMAGE_NAME:latest"
  rules:
    - if: '$CI_COMMIT_BRANCH'
